channels:
- defaults
- conda-forge

dependencies:
- requests
- astropy
- astropy-healpix
- matplotlib
- astroquery
- jupyter
- nbconvert
- nbformat
- pytest
- pytest-cov
- sphinx
- pip:
  - numpydoc
  - networkx
  - spherical_geometry
  - lark-parser
  - cdshealpix
